'use client';

import Link from 'next/link';
import { useLanguage } from '@/components/LanguageProvider';

const CONTENT = {
  nl: {
    title: 'Algemene Voorwaarden',
    updated: 'Laatst bijgewerkt: januari 2026',
    back: '← Terug naar home',
    other: 'Privacybeleid',
    otherHref: '/privacy',
    sections: [
      { title: '1. Gebruik van de dienst', content: 'Sollicitatie Coach biedt een AI-gedreven CV-analyseservice. Je mag de dienst uitsluitend gebruiken voor persoonlijke, niet-commerciële doeleinden — het verbeteren van je eigen sollicitaties. Het is niet toegestaan de service te gebruiken voor het in bulk genereren van motivatiebrieven namens anderen.' },
      { title: '2. Gratis gebruik en betaalde plannen', content: 'Het gratis plan biedt 3 analyses (eenmalig). Betaalde plannen (Plus en Pro) worden maandelijks gefactureerd via LemonSqueezy. Je kunt op elk moment opzeggen via je abonnementsbeheer. Na opzegging heb je tot het einde van de betaalde periode toegang.' },
      { title: '3. Aansprakelijkheid', content: 'De analyses en motivatiebrieven worden gegenereerd door AI en zijn indicatief van aard. Sollicitatie Coach garandeert geen specifieke resultaten (zoals aangenomen worden voor een functie). Je bent zelf verantwoordelijk voor de inhoud die je indient bij werkgevers.' },
      { title: '4. Intellectueel eigendom', content: 'De door AI gegenereerde content (analyses, motivatiebrieven) wordt eigendom van de gebruiker zodra deze is gegenereerd. De software, het platform en de merknaam "Sollicitatie Coach" zijn eigendom van de ontwikkelaar.' },
      { title: '5. Beschikbaarheid', content: 'We streven naar maximale beschikbaarheid maar garanderen geen 100% uptime. Geplande onderhoudswerkzaamheden worden waar mogelijk van tevoren aangekondigd.' },
      { title: '6. Wijzigingen', content: 'We kunnen deze voorwaarden op elk moment aanpassen. Bij significante wijzigingen ontvangen geregistreerde gebruikers een e-mailnotificatie. Voortgezet gebruik na wijziging geldt als akkoord.' },
      { title: '7. Toepasselijk recht', content: 'Op deze overeenkomst is Nederlands recht van toepassing. Geschillen worden voorgelegd aan de bevoegde rechter in Nederland.' },
    ],
  },
  en: {
    title: 'Terms and Conditions',
    updated: 'Last updated: January 2026',
    back: '← Back to home',
    other: 'Privacy Policy',
    otherHref: '/privacy',
    sections: [
      { title: '1. Use of the service', content: 'Sollicitatie Coach provides an AI-powered CV analysis service. You may only use the service for personal, non-commercial purposes — to improve your own job applications. It is not permitted to use the service to bulk-generate cover letters on behalf of others.' },
      { title: '2. Free use and paid plans', content: 'The free plan provides 3 analyses (one-time). Paid plans (Plus and Pro) are billed monthly via LemonSqueezy. You can cancel at any time through your subscription management. After cancellation, you retain access until the end of the paid period.' },
      { title: '3. Liability', content: 'Analyses and cover letters are generated by AI and are indicative in nature. Sollicitatie Coach does not guarantee specific outcomes (such as being hired for a position). You are solely responsible for the content you submit to employers.' },
      { title: '4. Intellectual property', content: 'AI-generated content (analyses, cover letters) becomes the property of the user once generated. The software, platform, and brand name "Sollicitatie Coach" are the property of the developer.' },
      { title: '5. Availability', content: 'We aim for maximum availability but do not guarantee 100% uptime. Planned maintenance will be announced in advance where possible.' },
      { title: '6. Changes', content: 'We may update these terms at any time. For significant changes, registered users will receive an email notification. Continued use after a change constitutes acceptance.' },
      { title: '7. Governing law', content: 'This agreement is governed by Dutch law. Disputes will be submitted to the competent court in the Netherlands.' },
    ],
  },
};

export default function TermsPage() {
  const { lang } = useLanguage();
  const c = CONTENT[lang];

  return (
    <div>
      <div style={{ background: 'linear-gradient(135deg,#0f172a,#1e3a8a)', padding: '56px 24px', textAlign: 'center' }}>
        <h1 style={{ color: '#fff', fontSize: 'clamp(1.8rem,3vw,2.4rem)', fontWeight: 900, letterSpacing: '-.03em', marginBottom: 10 }}>{c.title}</h1>
        <p style={{ color: '#94a3b8', fontSize: 15 }}>{c.updated}</p>
      </div>

      <div style={{ maxWidth: 720, margin: '0 auto', padding: '56px 24px 80px' }}>
        {c.sections.map((s, i) => (
          <div key={i} style={{ marginBottom: 36 }}>
            <h2 style={{ fontSize: '1.1rem', fontWeight: 700, color: '#0f172a', marginBottom: 10 }}>{s.title}</h2>
            <p style={{ fontSize: 15, color: '#475569', lineHeight: 1.75 }}>{s.content}</p>
          </div>
        ))}

        <div style={{ marginTop: 48, padding: '20px 24px', background: '#f8fafc', borderRadius: 14, border: '1px solid #e2e8f0' }}>
          <p style={{ fontSize: 14, color: '#64748b' }}>
            <Link href="/" style={{ color: '#4f46e5', fontWeight: 600 }}>{c.back}</Link>
            {' · '}
            <Link href={c.otherHref} style={{ color: '#4f46e5', fontWeight: 600 }}>{c.other}</Link>
          </p>
        </div>
      </div>
    </div>
  );
}
